name: "Quality"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

env:
  SONAR_EXCLUDES: src/index.ts **/scripts/*
  SONAR_BLACKLIST: .DS_Store config tresdoce-types

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16 ]
    name: "Setup"
    steps:
      - name: "⚙ Set up Node.js v${{ matrix.node }}"
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: "✅ Checkout repository"
        uses: actions/checkout@v2

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16 ]
    needs: setup
    name: "Build"
    steps:
      - name: "⚙ Set up Node.js v${{ matrix.node }}"
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: "✅ Checkout repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "💾 Restore Dependencies from cache"
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: "🦉 GitGuardian scan"
        uses: GitGuardian/ggshield-action@master
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

      - name: "📦 Install Dependencies"
        run: yarn install

      - name: "💅 Lint"
        run: yarn lint

      - name: "🔨 Build"
        run: yarn build

      - name: "👨‍💻 Run Test"
        run: |
          yarn sonar:properties -t monorepo --org ${{ github.repository_owner }} -p ${{ github.event.repository.name }} -b ${GITHUB_REF#refs/heads/} --bl ${SONAR_BLACKLIST} --ex ${SONAR_EXCLUDES}
          yarn test
        env:
          NODE_ENV: 'test'

      - name: "📊 Upload coverage report to Codecov"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: "📊 SonarCloud Scan"
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
